from pathlib import Path
import re

p=Path('index.html')
s=p.read_text()

if 'v29-uber-riderequest-coordinates' not in s:
    raise SystemExit('Expected v29 baseline not found; refusing unsafe Today UI patch')

css=r'''<style id="today-v30">
:root{--forest:#173f36;--forest2:#214f44;--cream:#fbfaf6;--paper:#fff;--gold:#b88447;--muted:#78867f;--line:#dddcd4}
body{background:var(--cream)}
.hero{min-height:76px;box-sizing:border-box;padding:0 30px;display:flex;align-items:center;justify-content:space-between;background:#fff;border-bottom:1px solid var(--line);position:sticky;top:0;z-index:20}
.hero small{font-size:13px;letter-spacing:.17em;font-weight:900;color:#173f36}.hero h1,.hero p{display:none}.hero:after{content:'4 travelers';font-size:13px;color:#77867f;letter-spacing:.02em}
#tabs{display:none!important}
main{padding:22px 28px 112px;max-width:820px}
.todayDash{background:linear-gradient(135deg,#173f36 0%,#205044 100%);border-radius:22px;padding:22px 20px 21px;color:#fff;margin:0 0 22px;box-shadow:0 1px 0 rgba(0,0,0,.03)}
.todayDashTop{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.todayDash small{color:#e1c698;font-size:10px;font-weight:900;letter-spacing:.16em}.todayDash h2{font:600 31px/1.05 Georgia,serif;margin:8px 0 8px}.todayDash .sub{font-size:13px;color:#e1e9e5;margin:0}.todayClock{text-align:right;white-space:nowrap}.todayClock strong{font-size:16px;letter-spacing:.03em}.todayClock span{display:block;font-size:10px;color:#b8c9c3;margin-top:8px}.dashPills{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.dashPills span{border:1px solid rgba(255,255,255,.24);background:rgba(255,255,255,.06);border-radius:999px;padding:8px 10px;font-size:10px;color:#f7f7f3}
.sectionHead{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:24px 2px 12px}.sectionHead h3{margin:0;font-size:12px;letter-spacing:.14em;font-weight:900;color:#173f36}.sectionHead button,.sectionHead span{border:0;background:none;color:#7b8982;font-size:11px;padding:0}
.wx{display:grid;grid-template-columns:repeat(3,minmax(148px,1fr));gap:10px;overflow-x:auto;scrollbar-width:none;padding-bottom:1px}.wx::-webkit-scrollbar{display:none}.wx .weatherCard{min-width:148px;background:#fff;border:1px solid #deddd5;border-radius:17px;padding:14px 13px 13px;box-sizing:border-box}.weatherTop{display:flex;justify-content:space-between;align-items:start}.weatherTop b{font-size:13px}.weatherEmoji{font-size:25px}.weatherTemp{font:600 28px Georgia,serif;margin:11px 0 2px}.weatherTemp small{font:400 10px -apple-system,BlinkMacSystemFont,sans-serif;color:#718078}.weatherDesc{font-size:10px;color:#718078}.rainPill{display:inline-flex;align-items:center;gap:4px;margin-top:9px;border:1px solid #e6e2d9;border-radius:999px;padding:5px 7px;font-size:9px;color:#708078}.weatherTip{font-size:9px;color:#906d3d;font-weight:800;line-height:1.35;margin-top:9px}
.anchorRail{display:grid;grid-auto-flow:column;grid-auto-columns:minmax(220px,72%);gap:10px;overflow-x:auto;scrollbar-width:none;padding-bottom:2px}.anchorRail::-webkit-scrollbar{display:none}.anchorCard{background:#fff;border:1px solid #deddd5;border-radius:17px;padding:14px 14px 16px;min-height:126px;box-sizing:border-box}.anchorCard.next{border-color:#b88447;box-shadow:inset 0 0 0 1px #b88447}.anchorTop{display:flex;justify-content:space-between;color:#b88447;font-size:9px;font-weight:800;letter-spacing:.05em}.anchorTop span:last-child{font-size:19px}.anchorCard h4{font-size:12px;margin:7px 0 3px}.anchorCard p{font-size:10px;color:#718078;line-height:1.35;margin:0}.anchorCount{font:600 25px Georgia,serif;margin-top:14px}.anchorCount small{font:400 9px -apple-system,BlinkMacSystemFont,sans-serif;color:#718078}
.daySwitch{display:flex;gap:8px;overflow-x:auto;scrollbar-width:none;margin:26px 0 20px}.daySwitch::-webkit-scrollbar{display:none}.daySwitch button{border:1px solid #deddd5;background:#fff;color:#173f36;border-radius:15px;padding:10px 12px;min-width:112px;text-align:left}.daySwitch button.on{background:#173f36;color:#fff;border-color:#173f36}.daySwitch small{display:block;font-size:8px;opacity:.7;margin-bottom:3px}.daySwitch b{font-size:11px}
.dayIntro{margin:4px 4px 15px}.dayIntro small{font-size:9px;color:#b88447;font-weight:900;letter-spacing:.15em}.dayIntro h2{font:600 32px/1.04 Georgia,serif;margin:7px 0 6px;color:#173f36}.dayIntro p{font-size:11px;color:#718078;margin:0;line-height:1.45}
.timeline{background:transparent;border:0;padding:0}.timeline .item{background:#fff;border:1px solid #deddd5;border-radius:15px;margin-bottom:9px;padding:13px 12px;grid-template-columns:27px 63px minmax(0,1fr)}.timeline .item>button{width:26px;height:26px;border-radius:50%;border:1px solid #d9d8d0;background:#fff;color:#173f36}.timeline h3{font-size:12px}.timeline p{font-size:9.5px}.bits div{background:#f6f3ec}.actions a{font-size:9px;padding:7px 10px}.bottom{padding:7px 18px max(8px,env(safe-area-inset-bottom));box-shadow:0 -4px 18px rgba(23,63,54,.03)}.bottom button{font-size:11px;min-height:58px}.bottom .on{background:transparent;color:#173f36;font-weight:900}
@media(max-width:430px){main{padding-left:15px;padding-right:15px}.hero{padding-left:20px;padding-right:20px}.hero small{font-size:11px}.hero:after{font-size:11px}.wx{grid-template-columns:repeat(3,minmax(132px,1fr))}.wx .weatherCard{min-width:132px}.todayDash h2{font-size:29px}.anchorRail{grid-auto-columns:76%}}
</style>'''
s=s.replace('</head>',css+'\n</head>',1)

# Hide the old top day strip; Today now owns its date switcher.
s=re.sub(r"function tabs\(\)\{.*?\}function nav\(\)","function tabs(){let t=document.getElementById('tabs');t.style.display='none';t.innerHTML=''}function nav()",s,count=1,flags=re.S)

# Richer weather cards, still using the same dependency-free Open-Meteo endpoint.
weather=r'''function wxText(c){if(c===0)return'Clear';if(c<=2)return'Partly cloudy';if(c===3)return'Cloudy';if(c===45||c===48)return'Fog';if(c>=51&&c<=57)return'Drizzle';if(c>=61&&c<=67)return'Rain';if(c>=71&&c<=77)return'Snow';if(c>=80&&c<=82)return'Showers';if(c>=95)return'Thunderstorms';return'Mixed'}
function wxTip(c,r){if(r>=40)return'☂️ Keep an umbrella handy';if(c===0||c<=2)return'🧴 Sunscreen + water';if(c===45||c===48)return'👟 Take it slow in fog';return'👟 Great walking weather'}
async function weather(){let h=document.getElementById('wx');if(!h)return;let P=[[38.72,-9.14,'Lisbon'],[41.15,-8.61,'Porto'],[38.8,-9.39,'Sintra']];h.innerHTML='<div class="weatherCard">Loading weather…</div>';try{let a=await Promise.all(P.map(async p=>{let u=`https://api.open-meteo.com/v1/forecast?latitude=${p[0]}&longitude=${p[1]}&current=temperature_2m,weather_code&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&temperature_unit=fahrenheit&timezone=auto&forecast_days=1`;let j=await(await fetch(u)).json();return{name:p[2],temp:Math.round(j.current.temperature_2m),code:j.current.weather_code,hi:Math.round(j.daily.temperature_2m_max[0]),lo:Math.round(j.daily.temperature_2m_min[0]),rain:j.daily.precipitation_probability_max[0]||0}}));h.innerHTML=a.map(x=>`<div class="weatherCard"><div class="weatherTop"><b>${x.name}</b><span class="weatherEmoji">${wxIcon(x.code)}</span></div><div class="weatherTemp">${x.temp}° <small>/ ${x.lo}°F</small></div><div class="weatherDesc">${wxText(x.code)}</div><div class="rainPill">💧 ${x.rain}% rain</div><div class="weatherTip">${wxTip(x.code,x.rain)}</div></div>`).join('')}catch(e){h.innerHTML='<div class="weatherCard">🌤️ Weather unavailable</div>'}}'''
s=re.sub(r"async function weather\(\)\{.*?\}function tabs\(\)",weather+"function tabs()",s,count=1,flags=re.S)

helpers=r'''function ptDateParts(){let parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Lisbon',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());let o={};parts.forEach(x=>o[x.type]=x.value);return{date:o.year+'-'+o.month+'-'+o.day,mins:Number(o.hour)*60+Number(o.minute),clock:new Intl.DateTimeFormat('en-US',{timeZone:'Europe/Lisbon',hour:'numeric',minute:'2-digit'}).format(new Date())}}
function tripDateIndex(date){return{'2026-08-17':0,'2026-08-18':1,'2026-08-19':2,'2026-08-20':3}[date]}
function rangeMins(t){let m=t.match(/(\d{1,2}):(\d{2})(?:–(\d{1,2}):(\d{2})| onward)?/);if(!m)return null;let a=Number(m[1])*60+Number(m[2]),b=m[3]?Number(m[3])*60+Number(m[4]):24*60;return[a,b]}
function liveState(){let z=ptDateParts(),di=tripDateIndex(z.date);if(di==null)return{label:'TRIP DASHBOARD',title:days[day].place,sub:days[day].date,pill:'Pre-cruise',place:days[day].place,clock:z.clock};let items=days[di].items,cur=null,next=null;for(let i=0;i<items.length;i++){let r=rangeMins(items[i][0]);if(!r)continue;if(z.mins>=r[0]&&z.mins<r[1]){cur=items[i];next=items[i+1]||null;break}if(z.mins<r[0]){next=items[i];break}}if(cur){let r=rangeMins(cur[0]),left=Math.max(0,r[1]-z.mins);return{label:'HAPPENING NOW',title:cur[2],sub:days[di].place+' · '+cur[0],pill:next?'Next in '+left+'m':'Current plan',place:days[di].place,clock:z.clock}}if(next){let r=rangeMins(next[0]),wait=Math.max(0,r[0]-z.mins);return{label:'UP NEXT',title:next[2],sub:days[di].place+' · '+next[0],pill:'Starts in '+wait+'m',place:days[di].place,clock:z.clock}}return{label:'DAY COMPLETE',title:'Wind down',sub:days[di].place,pill:'Tomorrow is ready',place:days[di].place,clock:z.clock}}
const anchors=[{date:'2026-08-18',time:'08:09',label:'08/18 · 08:09',title:'Porto outbound train',sub:'Lisboa Oriente → Porto Campanhã',icon:'🚆'},{date:'2026-08-18',time:'18:40',label:'08/18 · 18:40',title:'Porto return train',sub:'Porto Campanhã → Lisboa Oriente',icon:'🚆'},{date:'2026-08-19',time:'14:30',label:'08/19 · 14:30',title:'Quinta da Regaleira',sub:'Timed anchor in Sintra',icon:'🎟️'},{date:'2026-08-20',time:'16:00',label:'08/20 · 16:00',title:'Latest cruise check-in',sub:'Aim to board well before this',icon:'🛳️'}];
function anchorHtml(){let now=ptDateParts(),base=new Date(now.date+'T00:00:00Z');let arr=anchors.map(a=>{let d=new Date(a.date+'T'+a.time+':00Z'),mins=Math.round((d-base)/60000-now.mins);return{...a,mins}}).filter(a=>a.mins>-120).slice(0,3);if(!arr.length)arr=anchors.slice(-2).map(a=>({...a,mins:0}));return arr.map((a,i)=>{let txt=a.mins<=0?'Now':a.mins<60?a.mins+'m':a.mins<1440?Math.floor(a.mins/60)+'h '+a.mins%60+'m':Math.floor(a.mins/1440)+'d '+Math.floor((a.mins%1440)/60)+'h';return`<article class="anchorCard ${i===0?'next':''}"><div class="anchorTop"><span>${a.label}</span><span>${a.icon}</span></div><h4>${a.title}</h4><p>${a.sub}</p><div class="anchorCount">${txt} <small>to go</small></div></article>`}).join('')}
function dayIntroText(i){return[['MON, AUG 17 · ARRIVAL DAY','Lisbon · curated','Land, reset and explore Lisbon without overloading arrival day.'],['TUE, AUG 18 · PORTO DAY TRIP','Porto · curated','A high-to-low walking route built around your confirmed train times.'],['WED, AUG 19 · SINTRA DAY','Sintra · curated','Gardens, Regaleira and a realistic pace with transport buffers.'],['THU, AUG 20 · BELÉM + EMBARKATION','Belém · curated','MAAT and Belém first, then retrieve luggage and board Silver Muse early.']][i]}
'''

new_today=r'''function today(){let d=days[day],live=liveState(),intro=dayIntroText(day);return `<section class="todayDash"><div class="todayDashTop"><div><small>${live.label}</small><h2>${live.title}</h2><p class="sub">${live.sub}</p></div><div class="todayClock"><strong>${live.clock}</strong><span>Portugal time</span></div></div><div class="dashPills"><span>${live.pill}</span><span>${live.place}</span></div></section><div class="sectionHead"><h3>WEATHER FOR YOUR VISIT</h3><button onclick="weather()">↻ Refresh</button></div><div id="wx" class="wx"></div><div class="sectionHead"><h3>CRITICAL ANCHORS</h3><span>Portugal time</span></div><div class="anchorRail">${anchorHtml()}</div><div class="daySwitch">${days.map((x,i)=>`<button class="${i===day?'on':''}" onclick="day=${i};render()"><small>${x.date}</small><b>${x.place}</b></button>`).join('')}</div><section class="dayIntro"><small>${intro[0]}</small><h2>${intro[1]}</h2><p>${intro[2]}</p></section><section class="timeline">${d.items.map((x,i)=>`<article class="item"><button onclick="toggle('${day}-${i}')">${done[day+'-'+i]?'✓':'○'}</button><div><b>${x[1]}</b><br><small>${x[0]}</small></div><div><h3>${x[2]}</h3><p>${x[3]}</p><div class="bits"><div><b>SEE</b>${x[4]}</div><div><b>TRY / TIP</b>${x[5]}</div></div><div class="actions"><a target="_blank" href="${map(x[6])}">↗ Directions</a><a class="uber" href="${uber(x[6])}">Uber</a></div></div></article>`).join('')}</section>${foodSection()}`}'''

s=re.sub(r"function today\(\)\{.*?\}function cruisePage\(\)",helpers+new_today+"function cruisePage()",s,count=1,flags=re.S)

s=s.replace('content="v29-uber-riderequest-coordinates"','content="v30-today-reference-ui"',1)

# Safety checks: Today UI updated; non-Today functions and native Uber deep link remain.
checks=['v30-today-reference-ui','function cruisePage()','function local()','function list()','uber://riderequest','dropoff%5Blatitude%5D','todayDash','CRITICAL ANCHORS','WEATHER FOR YOUR VISIT']
for c in checks:
    if c not in s: raise SystemExit('Missing required marker: '+c)

p.write_text(s)
print('Today UI v30 patch applied safely')
